#!/bin/bash

read -p "id: " id
read -sp "pwd: " pwd

# Mac
open zoommtg:"//zoom.us/join?confno=${id}&pwd=${pwd}"

# Linux
# xdg-open zoommtg:"//zoom.us/join?confno=${id}&pwd=${pwd}"

echo "Now connecting..."
